version: '3.5'

services:
  gateway:
    image: nginx:stable
    ports:
      - '80:80'
      - '9000:9000'
    command: [ nginx, '-g', 'daemon off;' ]
    volumes:
      - ./nginx:/etc/nginx
  portainer:
    image: portainer/portainer
    command: --tlsskipverify
    volumes:
      - ./portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock